### ISSUE TITLE
`Task(parallel=n)` has surprising behavior

### ISSUE THREAD

**Issue by NeoLegends** [rwth-i6/sisyphus#129]
Consider the scenario `yield Task("run", args=list(range(100)), parallel=5)`. The current behavior is that Sisyphus will submit at maximum 5 jobs/runners into the queue in parallel and these runners will each then run 20 sub jobs (in a single Q submission).

I think this is very surprising for the following reasons:
1. The `rqmt` needs to take this batching into account and accordingly needs the job time increased. This makes the limited parallelism no longer an "implementation detail".
2. You do not get finished-markers for the individual subjobs, but only once all sub jobs in one submitted Q runner have finished. This means failing sub jobs can not be re-run individually, but only on a per-batch basis.

I would have expected Sisyphus to individually submit runners running a single sub job each, but hold their submission to the Q back as needed (just like with jobs whose dependencies haven't finished running yet). Maybe there is a good reason why it is done this way, and I'd love to know.

**Comment by michelwi** [comment]
I read several concerns or confusions here:

For 1. I agree that the rqmt should not depend on the way the job is run.

For 2. I generally do also agree that it would be nicer to have individual finished markers for each `arg`. But I see that then it becomes rather complicated to keep track of which "submitted job" should run which `arg`. Especially if you restart the manager while some submitted jobs are still in the queue. One could try to keep the mapping fix and still have individual markers, s.t. if a job is resumed it can restart with the failed `arg`.

Additionally there is the confusion about what the option should do in general:
Based on the docstring I would also have assumed that subtasks larger than `parallel` will be held back until other subtasks have finished. But if I think about it, then that functionality should rather be implemented on engine level than on Job level. Imagine you want to limit yourself to 100 jobs in the SGE in total, then you would have to set the `parallel` option depending on how many Experiments you plan at the moment.

On the other hand the task-stacking makes sense on a per-Job basis. If you know that one particular task runs very fast but do not want to clutter the cluster with heaps of 5 minute submits (and/or want to avoid scheduling overhead), then they can easily be stacked into few longer running submits. 

So I would conclude that the documentation here should be improved, but the functionality is correct (or makes sense) here. The functionality you expected I would rather implement in the engine.

**Comment by critias** [comment]
I agree with @michelwi, if I remember correctly @curufinwe added this feature a long time ago to have a simple way to group many small tasks into fewer but larger tasks and that's what it does. I don't remember using it myself.

For 1.: It shouldn't be much work to simply multiply the time requirements by the number of tasks executed in the largest block to fix this. I guess adding something like `time = time*ceil(len(task._args) / task._parallel)` at the right place could fix that. The main problem I see here is that, if the original requirements are given with some headroom for each task, the final requested time could be really large.

For 2.: Having an own id per given argument would be nice, but it looks like adding that would be more complicated. Currently the task id is given by the engine, so that would have to be caught and overwritten if parallel jobs are used. I doubt this minor improvement is worth spending the time which would be needed to change and test it, but feel free to give it a try if you like.
