### ISSUE TITLE
Probably it would make sense to add the actual install command to the installation section

### ISSUE THREAD

**Issue by jvhoffbauer** [rwth-i6/sisyphus#45]
For newbies it is sometimes hard to infer, what might be clear for people working with such packages since a long time. 
Thus I would propose to add some more detail about how to install the actual package to the installation section, e.g. something like this:

```
git clone https://github.com/rwth-i6/sisyphus.git
pip install -e ~/code/sisyphus/
```

I can also prepare a pull request if you agree to this.

**Comment by critias** [comment]
Sure, please send your pull request. Just use a relative path for the install command instead of `~/code/sisyphus/`.

I welcome any improvement of the documentation. Also, if you come across any other parts that are unclear, it would be great if you mention it here or, even better, fix it and send a pull request.
