### ISSUE TITLE
Use config file from recipes directly

### ISSUE THREAD

**Issue by albertz** [rwth-i6/sisyphus#91]
Consider `i6_experiments.users....experiments...`.

In many cases, I don't need to have a separate config file. Or such a config while would basically only do an import, and maybe call some `run()` function and nothing else. However, in principle, I would want to directly do this:
```
sis m recipe/i6_experiments/...
```
But Sisyphus complains that it must be in the `config` directory.

Can we add support for that?

**Comment by JackTemaki** [comment]
In my current setup it is structured like:
`./sis m` -> run all experiments
`./sis m config.active` -> run all experiments I am currently working on
`./sis m config.librispeech.conformer` -> run my librispeech conformer experiments

**Comment by albertz** [comment]
I don't really understand your argumentation. I have config files just like you say, they are just in a different location, namely directly in `i6_experiments`.

Also, I don't understand the argumentation, why it would be bad to add this flexibility? Or if you did not say that, why is it relevant what you said?

Also, I don't understand the argument, why is having overhead a good thing?

**Comment by JackTemaki** [comment]
If you prefer to have this exact structure somewhere else, just symlink it as config folder.

**Comment by albertz** [comment]
A symlink would not work because I use relative imports.

**Comment by albertz** [comment]
> I wont spend time on this but feel free to do so

@christophmluscher I thought you actually also use it exactly this way, or not?

**Comment by christophmluscher** [comment]
no I use symlinks. but then I dont use relativ imports. I dont like `./sis m recipe/i6_experiments/users/luescher/configs/lilbrispeech/...`, I prefer `./sis  m config/...`

**Comment by critias** [comment]
The check was added since there used to be an internal reason that config and recipes had to be separated. I don't know of any technical reason for that anymore in the current code base. The cleaner also shouldn't care where the config file is located once the graph is loaded.

That said: I don't think it's a good idea to put your config files into the recipe folder, but I also don't think that it's my decision to make which convention you should follow.

You could just remove the assertion and try it.
